<?php return array(
    'root' => array(
        'name' => 'lawrence-deo/gym-management-system',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '09e559124dc5e1f8b1ffaa0bf9b6b72bb77f0801',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'bacon/bacon-qr-code' => array(
            'pretty_version' => 'v3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'f9cc1f52b5a463062251d666761178dbdb6b544f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bacon/bacon-qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dasprid/enum' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '8dfd07c6d2cf31c8da90c53b83c026c7696dda90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dasprid/enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'endroid/qr-code' => array(
            'pretty_version' => '6.0.2',
            'version' => '6.0.2.0',
            'reference' => '86f264ac7f88e06352d046e5b72b441f28bfa5d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../endroid/qr-code',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lawrence-deo/gym-management-system' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '09e559124dc5e1f8b1ffaa0bf9b6b72bb77f0801',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
